version: '3'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env

  worker:
    build: .
    command: celery -A myproject worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env

  redis:
    image: redis:alpine

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
