name: Django CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set environment variables and run the application
      - name: Run Django Application
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Access the OpenAI key from GitHub Secrets
        run: |
          echo "Running Django with OpenAI key: $OPENAI_API_KEY"
          python manage.py migrate  # Apply migrations before starting the server
          python manage.py runserver 0.0.0.0:8000  # Run the Django app on the GitHub Actions runner

      - name: Print OpenAI Key (For Debugging Only - REMOVE before Production)
        run: echo $OPENAI_API_KEY
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
